
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		PAULO DEVIDE
-- Create date: 20-JUN-2019
-- Description:	DECREMENTA O ESTOQUE NO PRODUTO
-- =============================================
CREATE TRIGGER dbo.INS_TGR_VENDAS  
   ON  DBO.VENDAS 
   AFTER INSERT
AS 
BEGIN
	
	SET NOCOUNT ON;
	DECLARE @ID_PRODUTO INT
	DECLARE @QUANT INT
	SELECT	@ID_PRODUTO=I.ID_PRODUTO, 
			@QUANT = I.QUANTIDADE  
	FROM inserted I

	UPDATE PRODUTOS SET QUANTIDADE = QUANTIDADE - @QUANT
	WHERE ID_PRODUTO = @ID_PRODUTO
	SET NOCOUNT OFF;
END
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		PAULO DEVIDE
-- Create date: 20-JUN-2019
-- Description:	RETORNA A QUANTIDADE EXCLUIDA 
--              PARA O ESTOQUE DO PRODUTO
-- =============================================
CREATE TRIGGER dbo.DEL_TGR_VENDAS  
   ON  DBO.VENDAS 
   AFTER DELETE
AS 
BEGIN
	
	SET NOCOUNT ON;
	DECLARE @ID_PRODUTO INT
	DECLARE @QUANT INT
	SELECT	@ID_PRODUTO=D.ID_PRODUTO, 
			@QUANT = D.QUANTIDADE  
	FROM DELETED D

	UPDATE PRODUTOS SET QUANTIDADE = QUANTIDADE + @QUANT
	WHERE ID_PRODUTO = @ID_PRODUTO
	SET NOCOUNT OFF;
END
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		PAULO DEVIDE
-- Create date: 20-JUN-2019
-- Description:	RETORNA A QUANTIDADE EXCLUIDA 
--              PARA O ESTOQUE DO PRODUTO
-- =============================================
CREATE TRIGGER dbo.UPD_TGR_VENDAS  
   ON  DBO.VENDAS 
   AFTER UPDATE
AS 
BEGIN
	
	SET NOCOUNT ON;
	DECLARE @ID_PRODUTO INT
	DECLARE @QUANT_NEW INT, @QUANT_OLD INT
	
	SELECT	@ID_PRODUTO=I.ID_PRODUTO, 
			@QUANT_NEW = I.QUANTIDADE  
	FROM inserted I

		SELECT	@ID_PRODUTO=D.ID_PRODUTO, 
			@QUANT_OLD = D.QUANTIDADE  
	FROM DELETED D

	UPDATE PRODUTOS SET QUANTIDADE = QUANTIDADE + @QUANT_OLD
	WHERE ID_PRODUTO = @ID_PRODUTO

	UPDATE PRODUTOS SET QUANTIDADE = QUANTIDADE - @QUANT_NEW
	WHERE ID_PRODUTO = @ID_PRODUTO

	SET NOCOUNT OFF;
END
GO

